window.recipes = [
  {
    title: "Spanakopita",
    category: "Savory Pie",
    time: "75 min",
    description:
      "Flaky phyllo layered with spinach, feta, scallions, dill, and olive oil.",
    tags: ["vegetarian", "phyllo", "feta", "classic"],
    ingredients: ["spinach", "feta", "dill", "phyllo"],
    image: "images/spanakopita.jpg",
  },
  {
    title: "Chicken Souvlaki",
    category: "Grill",
    time: "35 min",
    description:
      "Lemon-oregano chicken skewers with warm pita, tomato, onion, and tzatziki.",
    tags: ["grill", "weeknight", "pita", "lemon"],
    ingredients: ["chicken", "oregano", "lemon", "pita"],
    image: "images/chicken-souvlaki.jpg",
  },
  {
    title: "Tzatziki",
    category: "Dip",
    time: "15 min",
    description:
      "Thick Greek yogurt with cucumber, garlic, dill, lemon, and a good olive oil finish.",
    tags: ["dip", "yogurt", "vegetarian", "quick"],
    ingredients: ["yogurt", "cucumber", "garlic", "dill"],
    image: "images/tzatziki.jpg",
  },
  {
    title: "Gemista",
    category: "Baked",
    time: "95 min",
    description:
      "Tomatoes and peppers stuffed with herbed rice, vegetables, and olive oil.",
    tags: ["vegetarian", "rice", "baked", "summer"],
    ingredients: ["tomatoes", "peppers", "rice", "parsley"],
    image: "images/gemista.jpg",
  },
  {
    title: "Moussaka",
    category: "Comfort Food",
    time: "2 hr",
    description:
      "Layered eggplant, spiced meat sauce, potatoes, and creamy bechamel.",
    tags: ["baked", "classic", "eggplant", "dinner"],
    ingredients: ["eggplant", "potato", "beef", "bechamel"],
    image: "images/moussaka.jpg",
  },
  {
    title: "Greek Village Salad",
    category: "Salad",
    time: "10 min",
    description:
      "Tomatoes, cucumber, onion, olives, feta, oregano, and olive oil.",
    tags: ["salad", "vegetarian", "quick", "feta"],
    ingredients: ["tomatoes", "cucumber", "olives", "feta"],
    image: "images/greek-village-salad.jpg",
  },
];

const recipeDetails = {
  Spanakopita: {
    slug: "spanakopita",
    published: "May 30, 2026",
    prepTime: "25 minutes",
    cookTime: "50 minutes",
    totalTime: "75 minutes",
    servings: "8 pieces",
    story: [
      "Spanakopita is the kind of savory pie that belongs in the center of the table. The filling is bright with dill and scallions, rich with feta, and wrapped in crisp layers of phyllo.",
      "Serve it warm for dinner with a salad, or cut it into smaller squares for a party plate.",
    ],
    detailsTitle: "What makes it work",
    details: [
      "Squeeze the spinach well so the filling stays rich instead of watery.",
      "Brush every few layers of phyllo with olive oil for crisp, flaky edges.",
      "Let the pie rest before slicing so the filling sets cleanly.",
    ],
    ingredientsList: [
      "2 pounds spinach, cooked and squeezed dry",
      "8 ounces feta, crumbled",
      "4 scallions, thinly sliced",
      "1/2 cup chopped dill",
      "2 eggs, lightly beaten",
      "1 package phyllo dough, thawed",
      "1/2 cup olive oil",
      "Black pepper",
    ],
    instructions: [
      "Heat oven to 375 F. Oil a 9x13-inch baking dish.",
      "Mix spinach, feta, scallions, dill, eggs, and black pepper in a bowl.",
      "Layer half the phyllo in the dish, brushing every few sheets with olive oil.",
      "Spread the spinach filling evenly over the phyllo.",
      "Top with remaining phyllo, brushing with olive oil as you layer.",
      "Score the top, then bake until deeply golden and crisp.",
      "Rest 10 minutes before slicing.",
    ],
  },
  "Chicken Souvlaki": {
    slug: "chicken-souvlaki",
    published: "May 30, 2026",
    prepTime: "20 minutes",
    cookTime: "15 minutes",
    totalTime: "35 minutes",
    servings: "4 servings",
    story: [
      "Chicken souvlaki is fast, bright, and built for warm pita. A lemon-oregano marinade keeps the chicken juicy and gives the skewers their classic Greek flavor.",
      "Add tomato, onion, and tzatziki, then let everyone build their own plate.",
    ],
    detailsTitle: "The simple marinade",
    details: [
      "Lemon juice and olive oil season the chicken without making it heavy.",
      "Oregano, garlic, and salt do most of the work.",
      "A hot grill or skillet gives the skewers browned edges while keeping the inside tender.",
    ],
    ingredientsList: [
      "1 1/2 pounds boneless chicken thighs or breast, cubed",
      "3 tablespoons olive oil",
      "2 tablespoons lemon juice",
      "2 garlic cloves, grated",
      "2 teaspoons dried oregano",
      "1 teaspoon kosher salt",
      "Warm pita, tomato, onion, and tzatziki, for serving",
    ],
    instructions: [
      "Toss chicken with olive oil, lemon juice, garlic, oregano, and salt.",
      "Marinate for at least 20 minutes.",
      "Thread chicken onto skewers.",
      "Grill or sear over medium-high heat until browned and cooked through.",
      "Serve with pita, tomato, onion, and tzatziki.",
    ],
  },
  Tzatziki: {
    slug: "tzatziki",
    published: "May 30, 2026",
    prepTime: "15 minutes",
    cookTime: "0 minutes",
    totalTime: "15 minutes",
    servings: "2 cups",
    story: [
      "Tzatziki is cool, garlicky, and useful with almost everything: grilled meat, vegetables, pita, rice bowls, or roasted potatoes.",
      "The key is thick yogurt and cucumber that has been salted and squeezed.",
    ],
    detailsTitle: "Keep it thick",
    details: [
      "Use Greek yogurt so the dip starts creamy.",
      "Salt the cucumber and squeeze out the liquid before mixing.",
      "Chill before serving so the garlic and dill settle into the yogurt.",
    ],
    ingredientsList: [
      "2 cups Greek yogurt",
      "1 cucumber, grated",
      "1 garlic clove, grated",
      "2 tablespoons chopped dill",
      "1 tablespoon lemon juice",
      "1 tablespoon olive oil",
      "Kosher salt",
    ],
    instructions: [
      "Salt the grated cucumber and let it sit for 10 minutes.",
      "Squeeze out as much liquid as possible.",
      "Stir cucumber with yogurt, garlic, dill, lemon juice, olive oil, and salt.",
      "Chill until ready to serve.",
    ],
  },
  Gemista: {
    slug: "gemista",
    published: "May 30, 2026",
    prepTime: "30 minutes",
    cookTime: "65 minutes",
    totalTime: "95 minutes",
    servings: "6 servings",
    story: [
      "Gemista is a summer baking dish built around tomatoes, peppers, rice, herbs, and olive oil.",
      "The vegetables soften into the rice as they bake, making the filling fragrant and the pan juices perfect for spooning over each serving.",
    ],
    detailsTitle: "A flexible filling",
    details: [
      "Use ripe tomatoes and sturdy bell peppers.",
      "Do not fully cook the rice before baking; it finishes inside the vegetables.",
      "Add potatoes around the pan if you want a heartier meal.",
    ],
    ingredientsList: [
      "6 large tomatoes or bell peppers",
      "1 cup short-grain rice",
      "1 onion, grated",
      "2 garlic cloves, minced",
      "1/2 cup chopped parsley",
      "1/4 cup chopped mint",
      "1/2 cup olive oil",
      "1 cup crushed tomatoes",
      "Salt and black pepper",
    ],
    instructions: [
      "Heat oven to 375 F. Cut tops from tomatoes or peppers and hollow them out.",
      "Mix rice, onion, garlic, herbs, olive oil, crushed tomatoes, salt, and pepper.",
      "Fill vegetables loosely with the rice mixture.",
      "Arrange in a baking dish and drizzle with olive oil.",
      "Bake until vegetables are tender and rice is cooked.",
      "Rest 10 minutes before serving.",
    ],
  },
  Moussaka: {
    slug: "moussaka",
    published: "May 30, 2026",
    prepTime: "45 minutes",
    cookTime: "75 minutes",
    totalTime: "2 hours",
    servings: "8 servings",
    story: [
      "Moussaka is a layered Greek comfort dish with eggplant, potatoes, spiced meat sauce, and creamy bechamel.",
      "It takes time, but the finished dish slices beautifully and tastes even better after it rests.",
    ],
    detailsTitle: "Build the layers",
    details: [
      "Roast the eggplant instead of frying for an easier version.",
      "Season the meat sauce with cinnamon and oregano for warmth.",
      "Let the finished moussaka rest before cutting so the layers hold.",
    ],
    ingredientsList: [
      "2 eggplants, sliced",
      "2 potatoes, sliced",
      "1 pound ground beef or lamb",
      "1 onion, diced",
      "2 garlic cloves, minced",
      "1 cup crushed tomatoes",
      "1/2 teaspoon cinnamon",
      "1 teaspoon oregano",
      "3 cups bechamel sauce",
      "Salt, pepper, and olive oil",
    ],
    instructions: [
      "Heat oven to 400 F. Roast eggplant and potatoes with olive oil until tender.",
      "Cook onion, garlic, and meat until browned.",
      "Add tomatoes, cinnamon, oregano, salt, and pepper. Simmer until thick.",
      "Layer potatoes, eggplant, and meat sauce in a baking dish.",
      "Spread bechamel over the top.",
      "Bake until bubbling and golden.",
      "Rest at least 20 minutes before slicing.",
    ],
  },
  "Greek Village Salad": {
    slug: "greek-village-salad",
    published: "May 30, 2026",
    prepTime: "10 minutes",
    cookTime: "0 minutes",
    totalTime: "10 minutes",
    servings: "4 servings",
    story: [
      "Greek village salad is simple by design: ripe tomatoes, cucumber, onion, olives, feta, oregano, and olive oil.",
      "There is no lettuce here, just crunchy vegetables and a salty feta finish.",
    ],
    detailsTitle: "Use good produce",
    details: [
      "Cut vegetables into generous pieces so the salad stays rustic.",
      "Use a block of feta instead of crumbles.",
      "Let the tomato juices mix with olive oil at the bottom of the bowl.",
    ],
    ingredientsList: [
      "4 ripe tomatoes, cut into wedges",
      "1 cucumber, sliced",
      "1/2 red onion, thinly sliced",
      "1 cup Kalamata olives",
      "6 ounces feta",
      "1 teaspoon dried oregano",
      "3 tablespoons olive oil",
      "Red wine vinegar, optional",
    ],
    instructions: [
      "Arrange tomatoes, cucumber, onion, and olives in a shallow bowl.",
      "Top with feta.",
      "Sprinkle with oregano.",
      "Drizzle with olive oil and a splash of vinegar if using.",
      "Serve immediately with bread.",
    ],
  },
};

window.recipes = window.recipes.map((recipe) => ({
  ...recipe,
  ...(recipeDetails[recipe.title] || {}),
}));
